# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(blank=True, default=b'', max_length=100)),
                ('opis', models.CharField(blank=True, default=b'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eget mollis urna, imperdiet malesuada eros. Nunc eget mollis urna, imperdiet malesuada eros.', max_length=2000)),
                ('kategorija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svadba.Kategorija')),
            ],
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('fajl', models.ImageField(max_length=255, null=True, upload_to=b'myphoto/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='proizvod',
            name='slika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svadba.Slika'),
        ),
    ]
